server:
  port: 8090
spring:
  datasource:
    username: postgres
    password: root
    url:  jdbc:postgresql://localhost:5432/movieappauthdb
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


