server:
  port: 8889
spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: ${hs1gituri}
          default-label: master
          skip-ssl-validation: true
          username: ${hs1gitusername}
          password: ${hs1gitpassword}
