server:
  port: 8090
spring:
  rabbitmq:
    host: ${hs1rabbitmqhost}  #localhost
    port: ${hs1rabbitmqport}  #5672
    username: ${hs1rabbitmqusername}
    password: ${hs1rabbitmqpassword}
  security:
    user:
      name: hs1
      password: 123
  datasource:
    username: postgres
    password: root
    url: ${db_postgre_url}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${hs1jwtsecret}
  issuer: ${hs1jwtissuer}

redis:
  host: ${hs1redis}
  port: ${hs1redisport}
feign:
  user: ${hs1feignuser}
  elasticsearch: ${hs1feignelsatic}

rabbitmq:
  auth-exchange: "auth-exchange"
  register-binding-key: "register-binding-key"
  register-queue: "register-queue"
