server:
  port: 8095
spring:
  security:
    user:
      name: hs1
      password: 123
  datasource:
    username: postgres
    password: root
    url:  jdbc:postgresql://localhost:5432/movieappauthdb
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: bilgeadamsecretkey
  issuer: bilgeadam

