server:
  port: 8091

spring:
  rabbitmq:
    host: ${hs1rabbitmqhost}  #localhost
    port: ${hs1rabbitmqport}  #5672
    username: ${hs1rabbitmqusername}
    password: ${hs1rabbitmqpassword}
  data:
    mongodb:
      host: ${hs1mongohost}
      port: ${hs1mongoport}
      username: ${hs1mongousername}
      password: ${hs1mongopassword}
      database: ${hs1mongodb}
jwt:
  secret: ${hs1jwtsecret}
  issuer: ${hs1jwtissuer}

redis:
  host: ${hs1redis}
  port: ${hs1redisport}
feign:
  auth: ${hs1feignauth}
  elasticsearch: ${hs1feignelsatic}
rabbitmq:
  register-queue: "register-queue"