server:
  port: 8091

spring:
  data:
    mongodb:
      host: ${hs1mongohost}
      port: ${hs1mongoport}
      username: ${hs1mongousername}
      password: ${hs1mongopassword}
      database: ${hs1mongodb}
jwt:
  secret: ${hs1jwtsecret}
  issuer: ${hs1jwtissuer}

redis:
  host: ${hs1redis}
  port: ${hs1redisport}
feign:
  auth: ${hs1feignauth}
  elasticsearch: ${hs1feignelsatic}
